services:
  postgres:
    image: postgres:18
    container_name: expense_tracker_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker_dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data:
